name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm-and-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: yarn build:demo

      - name: Publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@plusone-masaki'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
